permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 余辉
  email: alvin.mi0620@gmail.com
  link: https://alvinmi.github.io
  # weibo: http://weibo.com/
  github: http://github.com/AlvinMi
  zhihu: https://www.zhihu.com/people/alvinmi/

# 站点信息
title: 余辉的博客
description: My personal blog.
url: https://alvinmi.github.io
rss_url: /pages/atom.xml

# gavatar 头像及 Favicon
gavatar: /public/img/gavatar.jpg
favicon: /public/img/favicon.ico

# google analytics 设置
ga:
  # id: UA-55089304-1 
  url: https://alvinmi.github.io

# disqus 设置
disqus:
  # comments: true,
  shortname: https-alvinmi-github-io

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - React
  - 摄影

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

gems:
  - jekyll-sitemap
  - jekyll-paginate

# gems: [jekyll-paginate]

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]